### PR TITLE
Fix handling for parameters and uncrustify code to keep readability

### PR DESCRIPTION
**Pull request by XeonDead**
1. Double (triple?) handling of argv leads to bad results (what you input isn't what you're getting)
2. Code can be re-formatted to improve readability (uncrustify is a good tool! using config from [here](https://gist.github.com/HybridRbt/bfcb99f64d8abee25ccabac66e472bc6))
3. No-args run says unmount, so it should do unmount. Not sure about writing parameters, but entering empty ones work. Feel free to improve that.

### CODE REVIEW

**Comment by nitanmarcel** [comment]
Umount is already handling when sending the default arguments to the `mount_iso` function, so I don't think it needs a separate function for that. Probably just add an empty `""` here which I think it was the case before I did the argument parsing. (https://github.com/nitanmarcel/isodrive/blob/ca08e351003794c9c16a1defb6666a541ea07af2/src/main.cpp#L8


Also thanks for the argument parsing, I suppose i forgot to remove the old one. 

But please make sure that the mount and umount are handled in the same function, by what I mentioned before, using the default values before parsing the arguments, as I intended to have it the first time I wrote this code. Having copy pasted code for most of the part becomes confusing to me :)

**Comment by XeonDead** [comment]
Derp, didn't think of that, sorry.
Let's redo it then.

**Comment by nitanmarcel** [comment]
> Derp, didn't think of that, sorry. Let's redo it then.

everything is umounted just fine if the file path is set empty. Just fix this to instead using `argv[1]` to  be `""`: `char *iso_target = (char *)"";` and it should be good, since it won't be overriden unless an argument is given

https://github.com/nitanmarcel/isodrive/blob/edf0d5fce51acf638a916a9286d5c092dc38894b/src/main.cpp#L8

which will result in setting an empty file path in https://github.com/nitanmarcel/isodrive/blob/edf0d5fce51acf638a916a9286d5c092dc38894b/src/configfsisomanager.cpp#L105 resulting in umount.


Which is basically this part from the original code written for the UT app

https://github.com/fredldotme/ISODriveUT/blob/master/src/configfsisomanager.cpp#L146

**Comment by XeonDead** [comment]
Ah, sure. Feel free to fix it yourself, then.

**Comment by nitanmarcel** [comment]
> Ah, sure. Feel free to fix it yourself, then.

This is what I was referring to when I was saying that the umount is already done by default if no arguments are given :)

https://github.com/nitanmarcel/isodrive/commit/4034ffebdc34a25cad30a345f895ad72e7dd9488

**Comment by XeonDead** [comment]
Oh, sorry. Didn't think of that, but thanks for following it up.

**Pull request merged**
